version: "3.7"
services:
  worker-boot:
    container_name: thesis_worker_boot
    build:
      dockerfile: Dockerfile
      context: ./workers/boot/
    ports:
      - 8082:8082
    depends_on: 
      - master
    environment: 
      - MASTER_HOST=master
      - MASTER_PORT=8080
      - WORKER_HOST=worker-boot
      - WORKER_PORT=8082
  worker-webflux:
    container_name: thesis_worker_webflux
    build:
      dockerfile: Dockerfile
      context: ./workers/webflux/
    ports:
      - 8081:8081
    depends_on: 
      - master
    environment: 
      - MASTER_HOST=master
      - MASTER_PORT=8080
      - WORKER_HOST=worker-webflux
      - WORKER_PORT=8081
  master:
    container_name: thesis_master
    build:
      dockerfile: Dockerfile
      context: ./master/spring/
    ports:
      - 8080:8080
    environment: 
      - MASTER_PORT=8080
      - MASTER_HOST=localhost
  jmeter:
    container_name: thesis_jmeter
    build:
      dockerfile: Dockerfile
      context: ./master/jmeter/
    volumes:
      - ./master/jmeter/test-results/:/jmeter/test-results/
    # entrypoint: "su"
    environment: 
      - HOST_ADRESS=worker-webflux
      - HOST_PORT=8081
  prometheus:
    ports:
    - "9090:9090"
    entrypoint: /bin/sh
    command: "/etc/prometheus/init_prometheus.sh"
    build:
      dockerfile: Dockerfile
      context: ./master/prometheus/
    environment: 
      - FIRST_WORKER_HOST=worker-webflux
      - FIRST_WORKER_PORT=8081
      - SECOND_WORKER_HOST=worker-boot
      - SECOND_WORKER_PORT=8082
