version: '3'

services:
  influxdb:
    container_name: influxdb
    build: influxdb
    ports:
      - '8086:8086'
      - '2003:2003'
    volumes:
      - ./influxdb/volume/:/var/lib/influxdb
  grafana:
    container_name: grafana
    build: grafana
    links:
      - influxdb
    ports:
      - '3000:3000'
  gatling:
    container_name: gatling
    build: gatling
    volumes:
      - ./gatling/results/:/build/target/gatling/
    depends_on: 
      - grafana

volumes:
  grafana_data: {}
